from groq import Groq
from dotenv import load_dotenv
import os, json, subprocess
from datetime import datetime

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))
GITHUB_REPO = "shivendrasurve/IntelliQA"
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")

def run_tests():
    result = subprocess.run(
        ["pytest", "test-suite/api-tests/", "-v", "--tb=short"],
        capture_output=True, text=True)
    return result.stdout + result.stderr, result.returncode

def parse_failures(output):
    failures = []
    for line in output.split("\n"):
        line = line.strip()
        if line.startswith("FAILED") and "::" in line:
            test = line.replace("FAILED ", "").split(" - ")[0].strip()
            failures.append(test)
    return failures

def get_error(output, test):
    short = test.split("::")[-1]
    lines = output.split("\n")
    capturing = False
    error = []
    for line in lines:
        if short in line and ("FAILED" in line or "AssertionError" in line or "Error" in line):
            capturing = True
        elif capturing:
            if line.strip().startswith("FAILED") or line.strip().startswith("====="):
                break
            if line.strip():
                error.append(line.strip())
    return error[:8]

def ai_analyse(test, error_lines):
    error_text = "\n".join(error_lines) if error_lines else "No error details captured"
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are a senior QA engineer. Be concise."},
            {"role": "user", "content": f"""Failed test: {test}
Error: {error_text}

Reply with EXACTLY these 5 lines:
FAILURE TYPE: (Server Error / Logic Error / Validation Error / Data Error)
ROOT CAUSE: (one sentence)
AFFECTED ENDPOINT: (e.g. POST /payments)
SEVERITY: (Critical / High / Medium / Low)
SUGGESTED FIX: (one sentence)"""}
        ])
    return response.choices[0].message.content

def create_issue(title, body):
    if not GITHUB_TOKEN:
        return None
    import urllib.request
    data = json.dumps({"title": title, "body": body, "labels": ["bug","automated","intelliqa"]}).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        data=data,
        headers={"Authorization": f"token {GITHUB_TOKEN}", "Content-Type": "application/json"},
        method="POST")
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read()).get("html_url")
    except Exception as e:
        print(f"Issue creation error: {e}")
        return None

if __name__ == "__main__":
    print("IntelliQA - AI Failure Analysis Engine")
    print("=" * 50)
    output, code = run_tests()

    if code == 0:
        print("All tests passed - no failures to analyse!")
        print(output[-300:])
    else:
        failures = parse_failures(output)
        print(f"Real failures detected: {len(failures)}")
        for f in failures:
            print(f"  - {f}")

        reports = []
        for i, test in enumerate(failures, 1):
            print(f"\n[{i}/{len(failures)}] Analysing: {test}")
            errors = get_error(output, test)
            analysis = ai_analyse(test, errors)
            print(analysis)
            title = f"[IntelliQA] Failed: {test.split('::')[-1]}"
            body = f"**Test:** `{test}`\n\n**AI Analysis:**\n{analysis}\n\n*Auto-generated by IntelliQA*"
            url = create_issue(title, body)
            print(f"Issue: {url or 'saved locally (no GITHUB_TOKEN)'}")
            reports.append({"test": test, "analysis": analysis, "issue": url, "timestamp": datetime.now().isoformat()})

        os.makedirs("execution-pipeline", exist_ok=True)
        with open("execution-pipeline/failure_report.json", "w") as f:
            json.dump(reports, f, indent=2)
        print(f"\nDone. {len(failures)} real failures analysed and saved.")